replaceitem entity @s slot.hotbar 0 air 0
replaceitem entity @s slot.hotbar 1 air 0
replaceitem entity @s slot.hotbar 2 air 0
replaceitem entity @s slot.hotbar 3 air 0
replaceitem entity @s slot.hotbar 4 air 0
replaceitem entity @s slot.hotbar 5 air 0
replaceitem entity @s slot.hotbar 6 air 0
replaceitem entity @s slot.hotbar 7 air 0
replaceitem entity @s slot.hotbar 8 air 0