replaceitem entity @a[tag=cinematicC] slot.hotbar 0 air 
replaceitem entity @a[tag=cinematicC] slot.hotbar 1 air 
replaceitem entity @a[tag=cinematicC] slot.hotbar 2 air 
replaceitem entity @a[tag=cinematicC] slot.hotbar 3 air
replaceitem entity @a[tag=cinematicC] slot.hotbar 4 air 
replaceitem entity @a[tag=cinematicC] slot.hotbar 5 air  
replaceitem entity @a[tag=cinematicC] slot.hotbar 6 air  
replaceitem entity @a[tag=cinematicC] slot.hotbar 7 air 
replaceitem entity @a[tag=cinematicC] slot.hotbar 8 air 
scoreboard players set "handler-g" cinematicB 1