execute as @s at @s if score "handler-o" cinematicB matches 15.. run function err/cinematic
execute as @s at @s if score "handler-o" cinematicB matches 14 run function hlp/bgk/cinematic_15
execute as @s at @s if score "handler-o" cinematicB matches 13 run function hlp/bgk/cinematic_14
execute as @s at @s if score "handler-o" cinematicB matches 12 run function hlp/bgk/cinematic_13
execute as @s at @s if score "handler-o" cinematicB matches 11 run function hlp/bgk/cinematic_12
execute as @s at @s if score "handler-o" cinematicB matches 10 run function hlp/bgk/cinematic_11
execute as @s at @s if score "handler-o" cinematicB matches 9 run function hlp/bgk/cinematic_10
execute as @s at @s if score "handler-o" cinematicB matches 8 run function hlp/bgk/cinematic_9
execute as @s at @s if score "handler-o" cinematicB matches 7 run function hlp/bgk/cinematic_8
execute as @s at @s if score "handler-o" cinematicB matches 6 run function hlp/bgk/cinematic_7
execute as @s at @s if score "handler-o" cinematicB matches 5 run function hlp/bgk/cinematic_6
execute as @s at @s if score "handler-o" cinematicB matches 4 run function hlp/bgk/cinematic_5
execute as @s at @s if score "handler-o" cinematicB matches 3 run function hlp/bgk/cinematic_4
execute as @s at @s if score "handler-o" cinematicB matches 2 run function hlp/bgk/cinematic_3
execute as @s at @s if score "handler-o" cinematicB matches 1 run function hlp/bgk/cinematic_2
execute as @s at @s if score "handler-o" cinematicB matches ..0 run function hlp/bgk/cinematic_1